=== 10MG/dsql/src/main/java/cn/tenmg/dsql/config/dsql.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.10mg.cn/schema/dsql"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.10mg.cn/schema/dsql"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
	<xsd:element name="dsqls">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="dsql" maxOccurs="unbounded"
					minOccurs="0" type="Dsql">
					<xsd:annotation>
						<xsd:documentation><![CDATA[动态结构化查询语言（DSQL）]]></xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="BasicParamHandler">
		<xsd:attribute name="params" type="xsd:string"
			use="required">
			<xsd:annotation>
				<xsd:documentation><![CDATA[参数名表达式。可使用 * 作为通配符，多个参数表达式之间使用逗号分隔。]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="ComparableFilter">
		<xsd:complexContent>
			<xsd:extension base="BasicParamHandler">
				<xsd:attribute name="value" type="xsd:string"
					use="required">
					<xsd:annotation>
						<xsd:documentation><![CDATA[供比较的值]]></xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Dsql">
		<xsd:sequence>
			<xsd:element name="converter" maxOccurs="1" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation><![CDATA[参数转换器]]></xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:choice>
						<xsd:element name="to-date" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[将参数转换为 java.util.Date 类型的转换器]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:extension base="BasicParamHandler">
										<xsd:attribute name="formatter"
											type="xsd:string" default="yyyy-MM-dd">
											<xsd:annotation>
												<xsd:documentation><![CDATA[格式模板（默认值yyyy-MM-dd）]]></xsd:documentation>
											</xsd:annotation>
										</xsd:attribute>
									</xsd:extension>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>

						<xsd:element name="date-add" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[时间参数加法运算转换器]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:extension base="BasicParamHandler">
										<xsd:attribute name="amount" type="xsd:int"
											use="required">
											<xsd:annotation>
												<xsd:documentation><![CDATA[时间量。为负值时，相当于减法]]></xsd:documentation>
											</xsd:annotation>
										</xsd:attribute>

										<xsd:attribute name="unit" default="day">
											<xsd:annotation>
												<xsd:documentation><![CDATA[时间单位]]></xsd:documentation>
											</xsd:annotation>
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:enumeration value="year">
														<xsd:annotation>
															<xsd:documentation>年</xsd:documentation>
														</xsd:annotation>
													</xsd:enumeration>
													<xsd:enumeration value="month">
														<xsd:annotation>
															<xsd:documentation>月</xsd:documentation>
														</xsd:annotation>
													</xsd:enumeration>
													<xsd:enumeration value="day">
														<xsd:annotation>
															<xsd:documentation>日</xsd:documentation>
														</xsd:annotation>
													</xsd:enumeration>
													<xsd:enumeration value="hour">
														<xsd:annotation>
															<xsd:documentation>时</xsd:documentation>
														</xsd:annotation>
													</xsd:enumeration>
													<xsd:enumeration value="minute">
														<xsd:annotation>
															<xsd:documentation>分</xsd:documentation>
														</xsd:annotation>
													</xsd:enumeration>
													<xsd:enumeration value="second">
														<xsd:annotation>
															<xsd:documentation>秒</xsd:documentation>
														</xsd:annotation>
													</xsd:enumeration>
													<xsd:enumeration value="millisecond">
														<xsd:annotation>
															<xsd:documentation>毫秒</xsd:documentation>
														</xsd:annotation>
													</xsd:enumeration>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:attribute>
									</xsd:extension>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>

						<xsd:element name="to-number" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[将参数值转换为数字类型的转换器]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:extension base="BasicParamHandler">
										<xsd:attribute name="formatter"
											type="xsd:string">
											<xsd:annotation>
												<xsd:documentation><![CDATA[格式模板。如#,###.00等]]></xsd:documentation>
											</xsd:annotation>
										</xsd:attribute>
									</xsd:extension>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>

						<xsd:element name="wrap-string" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[对 java.lang.String 类型参数进行包装的转换器]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:extension base="BasicParamHandler">
										<xsd:attribute name="formatter"
											default="%${value}%">
											<xsd:annotation>
												<xsd:documentation><![CDATA[包装模板（默认值%${value}%）]]></xsd:documentation>
											</xsd:annotation>
											<xsd:simpleType>
												<xsd:union memberTypes="NormalLikes xsd:string"></xsd:union>
											</xsd:simpleType>
										</xsd:attribute>
									</xsd:extension>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>

						<xsd:element name="to-string" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[将参数转换为 java.lang.String 类型的转换器]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:extension base="BasicParamHandler">
										<xsd:attribute name="formatter"
											type="xsd:string">
											<xsd:annotation>
												<xsd:documentation><![CDATA[格式模板。当参数值为 java.lang.Number、java.util.Date、java.util.Calendar 的实例时，通过格式模板将对象格式化为字符串。如 #,###.00、yyyy-MM-dd HH:mm:ss 等]]></xsd:documentation>
											</xsd:annotation>
										</xsd:attribute>
									</xsd:extension>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>

						<xsd:element name="split" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[将类型为 java.lang.String 的非 null 参数值进行分割的转换器]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:extension base="BasicParamHandler">
										<xsd:choice>
											<xsd:element name="regex" type="xsd:string"
												minOccurs="0" maxOccurs="1">
												<xsd:annotation>
													<xsd:documentation><![CDATA[regex 属性的替代。当遇到部分需要转义的字符时，可以使用该标签的 CDATA 来定义，以避免繁琐的转义]]>
													</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:choice>
										<xsd:attribute name="regex" type="xsd:string"
											default=",">
											<xsd:annotation>
												<xsd:documentation><![CDATA[字符串分割正则表达式。由于XML解析框架的原因，部分特殊字符需要转义。也可以使用 <regex> 子标签的 CDATA 来定义，以避免繁琐的转义]]></xsd:documentation>
											</xsd:annotation>
										</xsd:attribute>
										<xsd:attribute name="limit" type="xsd:integer">
											<xsd:annotation>
												<xsd:documentation><![CDATA[最大分割子字符串数。指定时，必须为大于1的正整数]]></xsd:documentation>
											</xsd:annotation>
										</xsd:attribute>
									</xsd:extension>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>

					</xsd:choice>
				</xsd:complexType>
			</xsd:element>

			<xsd:element name="filter" maxOccurs="1" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation><![CDATA[参数过滤器]]></xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:choice>
						<xsd:element name="blank" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[空白字符串参数过滤器]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:attribute name="params" type="xsd:string"
									default="*">
									<xsd:annotation>
										<xsd:documentation><![CDATA[参数名表达式。可使用 * 作为通配符，多个参数表达式之间使用逗号分隔。]]></xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>
							</xsd:complexType>
						</xsd:element>

						<xsd:element name="eq" maxOccurs="unbounded"
							minOccurs="0" type="ComparableFilter">
							<xsd:annotation>
								<xsd:documentation><![CDATA[等值参数过滤器]]></xsd:documentation>
							</xsd:annotation>
						</xsd:element>

						<xsd:element name="gt" maxOccurs="unbounded"
							minOccurs="0" type="ComparableFilter">
							<xsd:annotation>
								<xsd:documentation><![CDATA[大值参数过滤器]]></xsd:documentation>
							</xsd:annotation>
						</xsd:element>

						<xsd:element name="gte" maxOccurs="unbounded"
							minOccurs="0" type="ComparableFilter">
							<xsd:annotation>
								<xsd:documentation><![CDATA[大于等于参数过滤器]]></xsd:documentation>
							</xsd:annotation>
						</xsd:element>

						<xsd:element name="lt" maxOccurs="unbounded"
							minOccurs="0" type="ComparableFilter">
							<xsd:annotation>
								<xsd:documentation><![CDATA[小值参数过滤器]]></xsd:documentation>
							</xsd:annotation>
						</xsd:element>

						<xsd:element name="lte" maxOccurs="unbounded"
							minOccurs="0" type="ComparableFilter">
							<xsd:annotation>
								<xsd:documentation><![CDATA[小于等于参数过滤器]]></xsd:documentation>
							</xsd:annotation>
						</xsd:element>
					</xsd:choice>
				</xsd:complexType>
			</xsd:element>

			<xsd:element name="script" maxOccurs="1"
				type="xsd:string" minOccurs="1">
				<xsd:annotation>
					<xsd:documentation><![CDATA[动态结构化查询语言（DSQL）脚本]]></xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string"
			use="required">
			<xsd:annotation>
				<xsd:documentation><![CDATA[动态结构化查询语言（DSQL）编号]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:simpleType name="NormalLikes">
		<xsd:annotation>
			<xsd:documentation><![CDATA[常用LIKE参数包装枚举]]></xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="%${value}%"></xsd:enumeration>
			<xsd:enumeration value="%${value}"></xsd:enumeration>
			<xsd:enumeration value="${value}%"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== 10MG/dsql/src/test/resources/dsql/full-features.dsql.xml
<?xml version="1.0" encoding="utf-8"?>
<dsqls xmlns="http://www.10mg.cn/schema/dsql"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.10mg.cn/schema/dsql http://www.10mg.cn/schema/dsql.xsd">
	<dsql id="find_staff_info">
		<converter>
			<to-number params="enabled" formatter=""/>
			<to-string params="state" formatter="#" />
			<to-date params="beginDate,endDate" formatter="yyyy-MM-dd" />
			<date-add params="endDate" amount="1" unit="day" />
			<split params="positions" regex="," limit="500"/>
			<wrap-string params="staffName" formatter="%${value}%" />
		</converter>
		<filter>
			<blank params="null,emptyString,blankSpace"/>
			<eq value="0" params="eq,noteq"/>
			<gt value="0" params="gt,notgt"/>
			<gte value="0" params="gte,notgte"/>
			<lt value="0" params="lt,notlt"/>
			<lte value="0" params="lte,notlte"/>
		</filter>
		<script><![CDATA[
		SELECT
		  STAFF_ID,
		  STAFF_NAME,
		  POSITION,
		  STATE,
		  CREATE_TIME
		FROM STAFF_INFO
		WHERE enabled = :enabled
		  #[AND STATE = :state]
		  #[AND CREATE_TIME >= :beginDate]
		  #[AND CREATE_TIME < :endDate]
		  #[AND POSITION in (:positions)]
		  #[AND STAFF_NAME LIKE :staffName]
		  #[:null]
		  #[:emptyString]
		  #[:blankSpace]
		  #[:eq]
		  #[AND 0 != :noteq]
		  #[:gt]
		  #[AND 0 <= :notgt]
		  #[:gte]
		  #[AND 0 < :notgte]
		  #[:lt]
		  #[AND 0 >= :notlt]
		  #[:lte]
		  #[AND 0 > :notlte]
		ORDER BY STAFF_NAME
		]]></script>
	</dsql>
</dsqls>
